image: registry.gitlab.com/mpapp-private/manuscripts-frontend/node8-aws

stages:
  - deploy

deploy:
  stage: deploy
  script: scripts/deploy.sh
  tags:
    - nodejs-8
    - awscli
  only:
    - master

deploy_manual:
  stage: deploy
  script: scripts/deploy.sh
  tags:
    - nodejs-8
    - awscli
  when: manual
