image: node:12-buster

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - publish

build:
  stage: build
  script:
    - yarn install --frozen-lockfile --non-interactive
    - scripts/build.sh
  artifacts:
    paths:
      - dist
    expire_in: 1 day

publish:
  stage: publish
  dependencies:
    - build
  script:
    - npx @manuscripts/publish
  only:
    refs:
      - master
